sudo: required
dist: trusty
language: node_js
node_js:
  - '6.11'

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta
    - icnsutils
    - graphicsmagick

cache:
  directories:
  - node_modules
  - $HOME/.npm/_prebuilds
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - yarn install

script: 
  - export TRUE_COMMIT_MESSAGES=$(git log --oneline -2)
  - if [[ $TRUE_COMMIT_MESSAGES == *"build"* ]]; then echo 'building ..' && ./nightly.sh; fi;

  - echo 'Done!'
  
# Disable coveralls for now
after_script:
  - npm run coveralls

#deploy:
#  - provider: releases
#    api-key:
#      secure: <>
#    file:
#      - $TRAVIS_BUILD_DIR/dist.zip
#      - $TRAVIS_BUILD_DIR/dist.zip.sha256sum.txt
#    overwrite: true
#    on:
#      tags: true
