sudo: required
dist: trusty
language: node_js
node_js:
  - '9.2'

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta
    - icnsutils
    - graphicsmagick

cache:
  directories:
  - node_modules
  - $HOME/.npm/_prebuilds
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - export TRUE_COMMIT_MESSAGES=$(git log --oneline -2 | grep "+build")
  - export TRUE_COMMIT=$(echo $TRUE_COMMIT_MESSAGES | awk '{print $1}')
  - echo $TRUE_COMMIT_MESSAGES

  - yarn install
  - if [[ $TRUE_COMMIT_MESSAGES == *"+latest"* ]]; then yarn add https://github.com/particl/particl-market; fi;

script: 
  - echo 'Build Dist' && echo -en 'travis_fold:start:script.build\\r'
  - yarn build --base-href="./"
  - echo -en 'travis_fold:end:script.build\\r'
  
  - echo 'Lint Codebase' && echo -en 'travis_fold:start:script.lint\\r'
  - yarn run lint
  - echo -en 'travis_fold:end:script.lint\\r'
  
  - echo 'Test Codebase' && echo -en 'travis_fold:start:script.test\\r'
  - yarn run travis:test
  - echo -en 'travis_fold:end:script.test\\r'
  
  - if [[ $TRUE_COMMIT_MESSAGES == *"+build"* ]]; then ./nightly.sh; fi;

  - echo 'Done!'
  
# Disable coveralls for now
after_script:
  - npm run coveralls

#deploy:
#  - provider: releases
#    api-key:
#      secure: <>
#    file:
#      - $TRAVIS_BUILD_DIR/dist.zip
#      - $TRAVIS_BUILD_DIR/dist.zip.sha256sum.txt
#    overwrite: true
#    on:
#      tags: true
